### ISSUE TITLE
Can't compile with latest Emscripten

### ISSUE THREAD

**Issue by nbarkhina** [briancullinan/planet_quake#19]
Hi,

I went through all the steps in the Dockerfile to try and build the application from source. However I am getting an error on the step "make release PLATFORM=js". This is the error I am getting -

![image](https://user-images.githubusercontent.com/10982154/103138622-533bb400-46a2-11eb-86b6-6a37f90abebf.png)

Thanks

**Comment by briancullinan** [comment]
@nbarkhina removed from Makefile. Let me know if there is anything else! Thank you.
