### ISSUE TITLE
Syntax error when running pre-built docker container

### ISSUE THREAD

**Issue by XanderStrike** [briancullinan/planet_quake#23]
When attempting to run this project using the documented docker command:

```
docker run -ti -p 8080:8080 -p 27960:27960/udp briancullinan/quake3e:full
```

I receive the following error:

```
/bin/sh: 1: Syntax error: "&&" unexpected
```

This also occurs when attempting to mount a directory for assets:

```
docker run -ti -p 8080:8080 -p 27960:27960/udp -v ~/assets-clean/baseq3:/tmp/baseq3 --name quake3e briancullinan/quake3e:full
```

I took a quick look over the Dockerfile and I don't see anything that jumps out at me. Any ideas?

**Comment by briancullinan** [comment]
Sorry, just saw this. Lot's of big changes in the pipeline including a new build system.

**Comment by briancullinan** [comment]
> When attempting to run this project using the documented docker command:
> 
> ```
> docker run -ti -p 8080:8080 -p 27960:27960/udp briancullinan/quake3e:full
> ```
> 
> I receive the following error:
> 
> ```
> /bin/sh: 1: Syntax error: "&&" unexpected
> ```
> 
> This also occurs when attempting to mount a directory for assets:
> 
> ```
> docker run -ti -p 8080:8080 -p 27960:27960/udp -v ~/assets-clean/baseq3:/tmp/baseq3 --name quake3e briancullinan/quake3e:full
> ```
> 
> I took a quick look over the Dockerfile and I don't see anything that jumps out at me. Any ideas?

The new version I am working on for web will compile directly from C to WASM. No Emscripten, and I will package it all in a single index.html file. This new version doesn't have a repackaging requirement. It uses all the same source files, and you can also re-encode them to save transfer time if you want. The next version will use the Google storage API or plain HTML indexes to create a remote virtual file-system. 

And even more! The next version will act exactly the same as a native download, as it does in the web browser with very little code platform code.
