### ISSUE TITLE
Last commit that will compile to WebAssembly?

### ISSUE THREAD

**Issue by IoIxD** [briancullinan/planet_quake#29]
Currently getting this error when trying to compile to WASM. It's my understanding that the WASM part is no longer maintained (and I still want to use it anyways, but that's besides the point), but after downloading several versions of the code, I cannot find which version was last compiled successfully and pushed to [quake.games](https://quake.games)?

```
BOT_CC code/botlib/be_aas_bspq3.c
BOT_CC code/botlib/be_aas_cluster.c
BOT_CC code/botlib/be_aas_debug.c
BOT_CC code/botlib/be_aas_entity.c
BOT_CC code/botlib/be_aas_file.c
BOT_CC code/botlib/be_aas_main.c
BOT_CC code/botlib/be_aas_move.c
BOT_CC code/botlib/be_aas_reach.c
BOT_CC code/botlib/be_aas_optimize.c
BOT_CC code/botlib/be_aas_route.c
BOT_CC code/botlib/be_aas_routealt.c
BOT_CC code/botlib/be_aas_sample.c
BOT_CC code/botlib/be_ai_char.c
BOT_CC code/botlib/be_ai_chat.c
BOT_CC code/botlib/be_ai_gen.c
BOT_CC code/botlib/be_ai_goal.c
BOT_CC code/botlib/be_ai_move.c
BOT_CC code/botlib/be_ai_weap.c
BOT_CC code/botlib/be_ai_weight.c
BOT_CC code/botlib/be_ea.c
BOT_CC code/botlib/be_interface.c
BOT_CC code/botlib/l_crc.c
BOT_CC code/botlib/l_libvar.c
BOT_CC code/botlib/l_log.c
BOT_CC code/botlib/l_memory.c
BOT_CC code/botlib/l_script.c
BOT_CC code/botlib/l_precomp.c
make[2]: *** No rule to make target 'build/release-js-x86_64/client/jaricom.o', needed by 'build/release-js-x86_64/quake3e.x64'.  Stop.
make[2]: *** Waiting for unfinished jobs....
BOT_CC code/botlib/l_struct.c
make[2]: Leaving directory '/home/gavin/Sources/planet_quake'
make[1]: *** [Makefile:643: targets] Error 2
make[1]: Leaving directory '/home/gavin/Sources/planet_quake'
make: *** [Makefile:601: release] Error 2
```

**Comment by IoIxD** [comment]
I gave up on waiting for an answer so hard that I just started trying to get an old version of Emscripten/LLVM working so I can just use the original quake.js.

**Comment by briancullinan** [comment]
> I gave up on waiting for an answer so hard that I just started trying to get an old version of Emscripten/LLVM working so I could just use the original quake.js. I then began to sympathize with the creator and I don't think I will ever attempt anything relating to Emscripten ever again, these people are horrible are communication it would seem and it seems they remove functions for sport, sometimes without providing any reasonable alternative.

I talked to Inolen. All he wanted was a PR to fix binaryen -> llvm/clang transition. When I offered to help, he didn't want to work on the design, he only wanted a PR.

I'm sorry I haven't seen this sooner, but you closed it after 2 days. The last successful version I pushed to lvlworld and quake.games is tagged "working" here: https://github.com/briancullinan/planet_quake/tree/working

But wait! There's more! The new version I am working on for web. I haven't gotten a new build in over a year, so you're not the only one. This new version will compile directly from C to WASM. No Emscripten, and I will package it all in a single index.html file. This new version doesn't have a repackaging requirement. It uses all the same source files, and you can also re-encode them to save transfer time if you want. The next version will use the Google storage API or plain HTML indexes to create a remote virtual file-system. 

And even more! The next version will act exactly the same as a native download, as it does in the web browser with very little code platform code.
